# Form implementation generated from reading ui file 'Qt_Designer_ui_files/edit_percentages_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_percentages_dialog(object):
    def setupUi(self, edit_percentages_dialog):
        edit_percentages_dialog.setObjectName("edit_percentages_dialog")
        edit_percentages_dialog.resize(205, 290)
        self.edit_percentages_buttonBox = QtWidgets.QDialogButtonBox(parent=edit_percentages_dialog)
        self.edit_percentages_buttonBox.setGeometry(QtCore.QRect(20, 250, 156, 26))
        self.edit_percentages_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.edit_percentages_buttonBox.setObjectName("edit_percentages_buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=edit_percentages_dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 160, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.edit_percentages_formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.edit_percentages_formLayout.setContentsMargins(0, 0, 0, 0)
        self.edit_percentages_formLayout.setObjectName("edit_percentages_formLayout")

        self.retranslateUi(edit_percentages_dialog)
        QtCore.QMetaObject.connectSlotsByName(edit_percentages_dialog)

    def retranslateUi(self, edit_percentages_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_percentages_dialog.setWindowTitle(_translate("edit_percentages_dialog", "Edit Percentages"))
