# Form implementation generated from reading ui file 'Qt_Designer_ui_files/statistics_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Statistics_Dialog(object):
    def setupUi(self, Statistics_Dialog):
        Statistics_Dialog.setObjectName("Statistics_Dialog")

        self.retranslateUi(Statistics_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Statistics_Dialog)

    def retranslateUi(self, Statistics_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Statistics_Dialog.setWindowTitle(_translate("Statistics_Dialog", "Statistics"))
