# Form implementation generated from reading ui file 'Qt_Designer_ui_files/print_calculation_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 249)
        Dialog.setStatusTip("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 351, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classes_formLayout = QtWidgets.QFormLayout()
        self.classes_formLayout.setObjectName("classes_formLayout")
        self.horizontalLayout.addLayout(self.classes_formLayout)
        self.right_gridLayout = QtWidgets.QGridLayout()
        self.right_gridLayout.setObjectName("right_gridLayout")
        self.print_calculate_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.print_calculate_button.setMinimumSize(QtCore.QSize(0, 0))
        self.print_calculate_button.setObjectName("print_calculate_button")
        self.right_gridLayout.addWidget(self.print_calculate_button, 1, 0, 1, 2)
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 100))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber.setObjectName("lcdNumber")
        self.right_gridLayout.addWidget(self.lcdNumber, 2, 0, 1, 2)
        self.extras_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.extras_label.setWhatsThis("")
        self.extras_label.setObjectName("extras_label")
        self.right_gridLayout.addWidget(self.extras_label, 0, 0, 1, 1)
        self.extras_spinBox = CustomSpinBox(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extras_spinBox.sizePolicy().hasHeightForWidth())
        self.extras_spinBox.setSizePolicy(sizePolicy)
        self.extras_spinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.extras_spinBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.extras_spinBox.setFont(font)
        self.extras_spinBox.setStyleSheet("QSpinBox::up-button,\n"
"QSpinBox::down-button {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.extras_spinBox.setWrapping(False)
        self.extras_spinBox.setFrame(False)
        self.extras_spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.extras_spinBox.setReadOnly(False)
        self.extras_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.extras_spinBox.setObjectName("extras_spinBox")
        self.right_gridLayout.addWidget(self.extras_spinBox, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.right_gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Print Calculation"))
        self.print_calculate_button.setText(_translate("Dialog", "Calculate"))
        self.extras_label.setText(_translate("Dialog", "Extras:"))
from GUI_pyqt6.Widgets.Spin_Box import CustomSpinBox
